name: lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

permissions:
  pull-request: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - run: bun i --frozen-lockfile

      - run: bun run lint:es

      - run: bun run lint:prettier

      - run: bun run lint:ts

      # needed for `commitlint`
      - run: git fetch origin main

      - name: PR title | commitlint
        run: echo '${{ github.event.pull_request.title }}' | bunx commitlint
