name: test

on: pull_request

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - run: bun i --frozen-lockfile

      - run: bun run coverage

      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()
