name: test

on: pull_request

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc

      - run: bun i --frozen-lockfile

      - run: bun run coverage

      - uses: davelosert/vitest-coverage-report-action@704014293553d513b27ed5d6e4503dd4789b9ea9
        if: always()
